trigger: none


pool: AGENTPOOL



stages:

  - stage: 
    displayName: scanning 
    jobs:
      - job: scanning
        displayName: tfsec scanning
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)/enviroment/dev'
  - stage: Terraforminstaller
    displayName: terraform intall
    jobs:
      - job: installjob
        displayName: terraformintall
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
  - stage: Build 
    displayName: build stage
    jobs:
      - job: buildjob
        displayName: terraform init
        steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/dev'
            backendServiceArm: 'infraconnection'
            backendAzureRmResourceGroupName: 'dev-aks-rg'
            backendAzureRmStorageAccountName: 'infrastorage4480143'
            backendAzureRmContainerName: 'infracontainer'
            backendAzureRmKey: 'himanshu.tfstate'
        
        - task: TerraformTask@5
          displayName: terraform validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/dev'
        - task: TerraformTask@5
          displayName: terraform plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/dev'
            environmentServiceNameAzureRM: 'infraconnection'

  - stage: ManualApproval
    displayName: Manual Validation
    dependsOn: Build
    pool: server
    jobs:
    - job: ManualValidation
      displayName: Wait for approval
      steps:
        - task: ManualValidation@1
          timeoutInMinutes: 1440
          inputs:
            notifyUsers: |
              himaanshugupta01@gmail.com
            instructions: 'Please approve to proceed with Terraform Apply'

  - stage: 
    displayName: terraform apply
    jobs:
      - job: terraformapply
        displayName: terraform apply
        steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/dev'
            backendServiceArm: 'infraconnection'
            backendAzureRmResourceGroupName: 'dev-aks-rg'
            backendAzureRmStorageAccountName: 'infrastorage4480143'
            backendAzureRmContainerName: 'infracontainer'
            backendAzureRmKey: 'himanshu.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/dev'
            environmentServiceNameAzureRM: 'infraconnection'
        